"""Intel Brief LLM summary dry-run layer.

This module consumes the sanitized dry-run brief JSON generated by
``brief_builder`` and produces a summary evidence document. It can call the
existing LiteLLM routing layer when requested, but also supports a fallback-only
mode for safe controller tests.
"""

from __future__ import annotations

import json
import re
from collections.abc import Awaitable, Callable, Iterable
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.llm_routing_config import get_routing_profile, load_routing_config
from src.utils import scrub_secrets

CompletionFn = Callable[..., Awaitable[Any]]

DEFAULT_PROFILE = "intel_brief"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()  # noqa: UP017 - Python 3.10 worker compatibility


def _strip_think_tags(text: str) -> str:
    return re.sub(r"<think>.*?</think>", "", str(text or ""), flags=re.DOTALL).strip()


def _clean(value: Any) -> str:
    return str(value or "").strip()


def _safe_int(value: Any) -> int:
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        return 0


def _usage_dict(response: Any) -> dict[str, int]:
    usage = getattr(response, "usage", None)
    if usage is None and isinstance(response, dict):
        usage = response.get("usage")
    if usage is None:
        return {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

    def get(name: str) -> int:
        if isinstance(usage, dict):
            return _safe_int(usage.get(name))
        return _safe_int(getattr(usage, name, 0))

    prompt = get("prompt_tokens")
    completion = get("completion_tokens")
    total = get("total_tokens") or prompt + completion
    return {"prompt_tokens": prompt, "completion_tokens": completion, "total_tokens": total}


def _response_text(response: Any) -> str:
    if isinstance(response, str):
        return _strip_think_tags(response)
    if isinstance(response, dict):
        choices = response.get("choices") or []
        if choices:
            message = choices[0].get("message", {}) if isinstance(choices[0], dict) else {}
            return _strip_think_tags(message.get("content", ""))
    choices = getattr(response, "choices", []) or []
    if choices:
        message = getattr(choices[0], "message", None)
        return _strip_think_tags(getattr(message, "content", ""))
    return ""


def _item_line(item: dict[str, Any], index: int) -> str:
    details = "；".join(_clean(line) for line in item.get("detail_lines", []) if _clean(line))
    label = _clean(item.get("source_label")) or _clean(item.get("source")) or "未知来源"
    title = _clean(item.get("title")) or f"条目{index}"
    return f"{index}. [{label}] {title}" + (f"｜{details}" if details else "")


def build_intel_summary_prompt(
    items: list[dict[str, Any]],
    *,
    source_summaries: list[dict[str, Any]] | None = None,
    max_items: int = 15,
) -> str:
    """Build a concise Chinese prompt from verified dry-run items."""
    source_summaries = source_summaries or []
    source_lines = []
    for src in source_summaries:
        label = _clean(src.get("source_label")) or _clean(src.get("source"))
        worker = _clean(src.get("worker"))
        source_lines.append(f"- {label}: worker={worker}" if worker else f"- {label}")
    item_lines = [_item_line(item, idx) for idx, item in enumerate(items[:max_items], start=1)]
    return (
        "你是付费订阅产品《每日情报简报》的中文情报分析员。"
        "只能基于给定条目总结，不要编造、不要补充未出现的数据，不要输出推理过程。\n\n"
        "已验证数据源：\n"
        f"{chr(10).join(source_lines) if source_lines else '- 无'}\n\n"
        "待摘要条目：\n"
        f"{chr(10).join(item_lines) if item_lines else '无'}\n\n"
        "请输出：\n"
        "1. 一段 80-140 字总览；\n"
        "2. 3 条以内要点，每条必须引用条目里的具体名称或代码；\n"
        "3. 如果信息陈旧或样本少，明确写出边界。"
    )


def select_llm_family_for_profile(profile: dict[str, Any], *, available_families: Iterable[str] | None = None) -> str:
    """Pick the first profile family available in the current routing pool."""
    preferred = list(profile.get("preferred_families") or ["qwen", "g4f"])
    available = set(available_families or [])
    if available:
        for family in preferred:
            if family in available:
                return str(family)
    return str(preferred[0] if preferred else "qwen")


def _fallback_summary(items: list[dict[str, Any]]) -> str:
    if not items:
        return "本次没有可摘要条目。"
    titles = [_clean(item.get("title")) for item in items if _clean(item.get("title"))]
    first_titles = "；".join(titles[:3])
    sources = sorted({_clean(item.get("source_label")) for item in items if _clean(item.get("source_label"))})
    source_text = "、".join(sources) if sources else "已验证来源"
    return f"本次基于{source_text}共 {len(items)} 条已验证条目生成摘要草稿：{first_titles}。LLM 调用未成功或未启用，以上为抽取式降级摘要。"


async def summarize_items_with_llm(
    items: list[dict[str, Any]],
    *,
    source_summaries: list[dict[str, Any]] | None = None,
    profile: dict[str, Any] | None = None,
    available_families: Iterable[str] | None = None,
    completion_fn: CompletionFn | None = None,
    llm_attempted: bool = True,
    family_override: str | None = None,
) -> dict[str, Any]:
    """Summarize dry-run items via injected/current LiteLLM routing, with evidence."""
    profile = dict(profile or {})
    max_items = _safe_int(profile.get("max_input_items")) or 15
    max_tokens = _safe_int(profile.get("max_tokens")) or 700
    temperature = float(profile.get("temperature", 0.25))
    cache_ttl = _safe_int(profile.get("cache_ttl")) or 1800
    model_family = family_override or select_llm_family_for_profile(profile, available_families=available_families)
    prompt = build_intel_summary_prompt(items, source_summaries=source_summaries, max_items=max_items)

    if not llm_attempted:
        return {
            "status": "fallback",
            "llm_attempted": False,
            "llm_success": False,
            "model_family": model_family,
            "summary_text": _fallback_summary(items),
            "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
            "error_type": "not_attempted",
            "error": "fallback_only_mode",
            "prompt_chars": len(prompt),
        }

    if completion_fn is None:
        from src.litellm_router import free_pool

        if getattr(free_pool, "_router", None) is None:
            free_pool.initialize()
        available_families = set(getattr(free_pool, "sources", {}).keys())
        if family_override is None:
            model_family = select_llm_family_for_profile(profile, available_families=available_families)
        completion_fn = free_pool.acompletion

    try:
        response = await completion_fn(
            model_family=model_family,
            messages=[{"role": "user", "content": prompt}],
            system_prompt="你只做基于证据的中文情报摘要。",
            temperature=temperature,
            max_tokens=max_tokens,
            cache_ttl=cache_ttl,
        )
        text = _response_text(response)
        if not text:
            raise RuntimeError("empty_llm_response")
        return {
            "status": "success",
            "llm_attempted": True,
            "llm_success": True,
            "model_family": model_family,
            "summary_text": text,
            "usage": _usage_dict(response),
            "error_type": "",
            "error": "",
            "prompt_chars": len(prompt),
        }
    except Exception as exc:
        return {
            "status": "fallback",
            "llm_attempted": True,
            "llm_success": False,
            "model_family": model_family,
            "summary_text": _fallback_summary(items),
            "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
            "error_type": exc.__class__.__name__,
            "error": scrub_secrets(str(exc))[:500],
            "prompt_chars": len(prompt),
        }


def _load_profile(profile_name: str, config_path: str | Path | None = None) -> dict[str, Any]:
    config = load_routing_config(str(config_path) if config_path else None)
    profile = get_routing_profile(config, profile_name)
    if profile:
        return profile
    return {"preferred_families": ["qwen", "g4f"], "max_tokens": 700, "temperature": 0.25, "cache_ttl": 1800}


def _render_summary_markdown(result: dict[str, Any]) -> str:
    llm = result["llm"]
    lines = [
        "# Intel Brief LLM Summary Dry Run",
        "",
        f"- 生成时间：{result['timestamp']}",
        f"- 输入 dry-run 证据：`{result['input_dry_run_evidence']}`",
        f"- JSON证据：`{result['json_evidence']}`",
        f"- LLM状态：{llm['status']}；attempted={llm['llm_attempted']}；success={llm['llm_success']}；family={llm['model_family']}",
        "- 边界：No Telegram push；No scheduler registration；No production DB write。",
        "",
        "## LLM 摘要草稿",
        "",
        llm["summary_text"],
        "",
        "## 输入条目",
        "",
    ]
    for item in result["items"]:
        lines.append(f"- [{item.get('source_label', item.get('source', 'unknown'))}] {item.get('title', '')}")
    lines.extend(
        [
            "",
            "## 验证边界",
            "",
            "- 已执行：使用 dry-run evidence 中的真实采集条目构造摘要输入。",
            "- 未执行：Telegram 推送、scheduler 注册、常驻服务部署、生产 DB 写入。",
            "- 回滚边界：删除本次 LLM summary dry-run Markdown/JSON evidence 即可。",
            "",
        ]
    )
    return "\n".join(lines)


async def build_llm_summary_dry_run(
    *,
    dry_run_json_path: str | Path,
    markdown_output_path: str | Path,
    json_output_path: str | Path,
    stamp: str | None = None,
    profile_name: str = DEFAULT_PROFILE,
    profile: dict[str, Any] | None = None,
    available_families: Iterable[str] | None = None,
    completion_fn: CompletionFn | None = None,
    llm_attempted: bool = True,
    family_override: str | None = None,
) -> dict[str, Any]:
    """Build LLM summary dry-run Markdown/JSON evidence from brief dry-run JSON."""
    input_path = Path(dry_run_json_path)
    markdown_path = Path(markdown_output_path)
    json_path = Path(json_output_path)
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    items = [dict(item) for item in payload.get("items", []) if isinstance(item, dict)]
    source_summaries = [dict(src) for src in payload.get("source_summaries", []) if isinstance(src, dict)]
    profile = dict(profile or _load_profile(profile_name))
    llm = await summarize_items_with_llm(
        items,
        source_summaries=source_summaries,
        profile=profile,
        available_families=available_families,
        completion_fn=completion_fn,
        llm_attempted=llm_attempted,
        family_override=family_override,
    )
    result = {
        "timestamp": _now_iso(),
        "stamp": stamp or datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),  # noqa: UP017 - Python 3.10 worker compatibility
        "phase": "F-llm-summary-dry-run",
        "scope": "dry_run_items_to_llm_summary",
        "status": "success" if llm["llm_success"] else "partial_fallback",
        "profile_name": profile_name,
        "profile": profile,
        "input_dry_run_evidence": str(input_path),
        "output_markdown": str(markdown_path),
        "json_evidence": str(json_path),
        "input_summary": payload.get("summary", {}),
        "source_summaries": source_summaries,
        "items": items,
        "llm": llm,
        "limits": [
            "No Telegram push.",
            "No scheduler registration.",
            "No production DB write.",
            "Uses sanitized dry-run evidence as input; does not fetch external data sources.",
        ],
    }
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text(_render_summary_markdown(result), encoding="utf-8")
    json_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result
