"""
微信消息处理 API Router
挂载到 /api/v1/wechat/*

接收云端 wechat_receiver 转发的微信消息，调用 Brain/LLM 处理后返回回复。
"""

import logging
import os
import time
import re

from fastapi import APIRouter, Body
from typing import Dict, Any

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/wechat")


def _strip_g4f_ads(text: str) -> str:
    """清理 g4f 回复中的广告和思考标签"""
    # 移除 <think>...</think> 思考过程
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
    # 移除未闭合的 <think> 标签
    text = re.sub(r'<think>.*$', '', text, flags=re.DOTALL)
    # g4f 广告
    text = re.sub(r'\n*Need proxies cheaper than the market\?\s*\n*https?://op\.wtf\s*', '', text)
    text = re.sub(r'\n*Generated by .*?SUSPENDED.*?\n*', '', text)
    return text.strip()


@router.post("/incoming")
async def wechat_incoming(payload: Dict[str, Any] = Body(...)):
    """处理云端转发的微信消息

    请求体: {"from_user": "xxx@im.wechat", "text": "用户消息"}
    返回: {"reply": "AI 回复文本"}
    """
    from_user = payload.get("from_user", "")
    text = payload.get("text", "").strip()

    if not text:
        return {"reply": "你好！有什么可以帮你的吗？"}

    logger.info("[微信] 收到消息 from=%s...: %s", from_user[:15], text[:50])
    start = time.time()

    # 处理 /start 命令
    if text.lower() in ("/start", "你好", "hi", "hello"):
        return {"reply": "你好！我是 OpenClaw AI 助手 🤖\n\n"
                "我可以帮你：\n"
                "• 聊天对话\n"
                "• 比价查询（发\"帮我找便宜的 iPhone\"）\n"
                "• 回答问题\n\n"
                "直接发消息给我就行！"}

    # 微信场景优先速度：直接走 LLM，跳过 Brain（Brain 处理链路 30-90 秒太慢）
    reply = ""
    try:
        from src.litellm_router import free_pool
        response = await free_pool.acompletion(
            model_family="qwen",  # qwen 家族最快最稳
            messages=[
                {"role": "system", "content": "你是 OpenClaw AI 助手。用中文简洁友好地回答用户的问题。"},
                {"role": "user", "content": text},
            ],
            max_tokens=500,
        )
        llm_text = response.choices[0].message.content or ""
        if llm_text.strip():
            reply = llm_text.strip()
    except Exception as e:
        logger.warning("[微信] LLM 调用失败: %s", e)

    # 兜底
    if not reply.strip():
        reply = "抱歉，我暂时没能理解你的意思。换个方式再试试？"

    # 过滤广告
    reply = _strip_g4f_ads(reply)

    elapsed = round(time.time() - start, 2)
    logger.info("[微信] 回复生成 (%ss): %s...", elapsed, reply[:50])

    return {"reply": reply}
