"""微信消息处理 API Router。

接收云端 wechat_receiver 转发的微信消息，调用轻量 LLM 链路生成回复。
"""

import logging
import re
import time

from fastapi import APIRouter
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/wechat")


class WeChatIncomingRequest(BaseModel):
    """微信云端转发的消息体。"""

    from_user: str = Field(default="", max_length=256)
    text: str = Field(default="", max_length=4000)


class WeChatIncomingResponse(BaseModel):
    """返回给微信转发器的回复体。"""

    reply: str


def _strip_g4f_ads(text: str) -> str:
    """清理 g4f 回复中的广告和思考标签。"""
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    cleaned = re.sub(r"<think>.*$", "", cleaned, flags=re.DOTALL)
    cleaned = re.sub(r"\n*Need proxies cheaper than the market\?\s*\n*https?://op\.wtf\s*", "", cleaned)
    cleaned = re.sub(r"\n*Generated by .*?SUSPENDED.*?\n*", "", cleaned)
    return cleaned.strip()


async def _generate_wechat_reply(text: str) -> str | None:
    """微信场景走轻量 LLM 链路，避免完整 Brain 链路响应过慢。"""
    try:
        from src.litellm_router import free_pool

        response = await free_pool.acompletion(
            model_family="qwen",
            messages=[
                {"role": "system", "content": "你是 OpenClaw AI 助手。用中文简洁友好地回答用户的问题。"},
                {"role": "user", "content": text},
            ],
            max_tokens=500,
        )
        llm_text = response.choices[0].message.content or ""
        return llm_text.strip() or None
    except Exception as exc:
        logger.warning("[微信] LLM 调用失败: %s", exc)
        return None


@router.post("/incoming", response_model=WeChatIncomingResponse)
async def wechat_incoming(payload: WeChatIncomingRequest) -> WeChatIncomingResponse:
    """处理云端转发的微信消息。"""
    from_user = payload.from_user
    text = payload.text.strip()

    if not text:
        return WeChatIncomingResponse(reply="你好！有什么可以帮你的吗？")

    logger.info("[微信] 收到消息 from=%s...: %s", from_user[:15], text[:50])
    start = time.time()

    if text.lower() in ("/start", "你好", "hi", "hello"):
        return WeChatIncomingResponse(
            reply=(
                "你好！我是 OpenClaw AI 助手\n\n"
                "我可以帮你：\n"
                "- 聊天对话\n"
                "- 比价查询（发“帮我找便宜的 iPhone”）\n"
                "- 回答问题\n\n"
                "直接发消息给我就行！"
            )
        )

    reply = await _generate_wechat_reply(text)
    if not reply:
        reply = "抱歉，我暂时没能理解你的意思。换个方式再试试？"

    reply = _strip_g4f_ads(reply)
    elapsed = round(time.time() - start, 2)
    logger.info("[微信] 回复生成 (%ss): %s...", elapsed, reply[:50])
    return WeChatIncomingResponse(reply=reply)
